/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListProjects400Response,
  ListProjects401Response,
  ListProjects403Response,
  ListProjects404Response,
  ListProjects429Response,
  ListProjects500Response,
  OverviewMetrics,
} from '../models/index';
import {
    ListProjects400ResponseFromJSON,
    ListProjects400ResponseToJSON,
    ListProjects401ResponseFromJSON,
    ListProjects401ResponseToJSON,
    ListProjects403ResponseFromJSON,
    ListProjects403ResponseToJSON,
    ListProjects404ResponseFromJSON,
    ListProjects404ResponseToJSON,
    ListProjects429ResponseFromJSON,
    ListProjects429ResponseToJSON,
    ListProjects500ResponseFromJSON,
    ListProjects500ResponseToJSON,
    OverviewMetricsFromJSON,
    OverviewMetricsToJSON,
} from '../models/index';

export interface GetOverviewMetricsRequest {
    projectId: string;
}

/**
 * 
 */
export class ChartsMetricsApi extends runtime.BaseAPI {

    /**
     * This endpoint requires the following permission(s): `charts_metrics:overview:read`.
     * Get overview metrics for a project
     */
    async getOverviewMetricsRaw(requestParameters: GetOverviewMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OverviewMetrics>> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling getOverviewMetrics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/projects/{project_id}/metrics/overview`.replace(`{${"project_id"}}`, encodeURIComponent(String(requestParameters['projectId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OverviewMetricsFromJSON(jsonValue));
    }

    /**
     * This endpoint requires the following permission(s): `charts_metrics:overview:read`.
     * Get overview metrics for a project
     */
    async getOverviewMetrics(requestParameters: GetOverviewMetricsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OverviewMetrics> {
        const response = await this.getOverviewMetricsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
