/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Amazon type details
 * @export
 * @interface AmazonAppAmazon
 */
export interface AmazonAppAmazon {
    /**
     * The package name of the app
     * @type {string}
     * @memberof AmazonAppAmazon
     */
    packageName: string;
}

/**
 * Check if a given object implements the AmazonAppAmazon interface.
 */
export function instanceOfAmazonAppAmazon(value: object): boolean {
    if (!('packageName' in value)) return false;
    return true;
}

export function AmazonAppAmazonFromJSON(json: any): AmazonAppAmazon {
    return AmazonAppAmazonFromJSONTyped(json, false);
}

export function AmazonAppAmazonFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmazonAppAmazon {
    if (json == null) {
        return json;
    }
    return {
        
        'packageName': json['package_name'],
    };
}

export function AmazonAppAmazonToJSON(value?: AmazonAppAmazon | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'package_name': value['packageName'],
    };
}

