/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
import type { AmazonAppCreateAmazon } from "./AmazonAppCreateAmazon.ts";
import {
    AmazonAppCreateAmazonFromJSON,
    AmazonAppCreateAmazonFromJSONTyped,
    AmazonAppCreateAmazonToJSON,
} from "./AmazonAppCreateAmazon.ts";

/**
 * 
 * @export
 * @interface AmazonAppCreate
 */
export interface AmazonAppCreate {
    /**
     * 
     * @type {AmazonAppCreateAmazon}
     * @memberof AmazonAppCreate
     */
    amazon?: AmazonAppCreateAmazon;
}

/**
 * Check if a given object implements the AmazonAppCreate interface.
 */
export function instanceOfAmazonAppCreate(value: object): boolean {
    return true;
}

export function AmazonAppCreateFromJSON(json: any): AmazonAppCreate {
    return AmazonAppCreateFromJSONTyped(json, false);
}

export function AmazonAppCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmazonAppCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'amazon': json['amazon'] == null ? undefined : AmazonAppCreateAmazonFromJSON(json['amazon']),
    };
}

export function AmazonAppCreateToJSON(value?: AmazonAppCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amazon': AmazonAppCreateAmazonToJSON(value['amazon']),
    };
}

