/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
import type { AmazonAppAmazon } from "./AmazonAppAmazon.ts";
import {
    AmazonAppAmazonFromJSON,
    AmazonAppAmazonFromJSONTyped,
    AmazonAppAmazonToJSON,
} from "./AmazonAppAmazon.ts";
import type { AppStoreAppAppStore } from "./AppStoreAppAppStore.ts";
import {
    AppStoreAppAppStoreFromJSON,
    AppStoreAppAppStoreFromJSONTyped,
    AppStoreAppAppStoreToJSON,
} from "./AppStoreAppAppStore.ts";
import type { MacAppStoreAppMacAppStore } from "./MacAppStoreAppMacAppStore.ts";
import {
    MacAppStoreAppMacAppStoreFromJSON,
    MacAppStoreAppMacAppStoreFromJSONTyped,
    MacAppStoreAppMacAppStoreToJSON,
} from "./MacAppStoreAppMacAppStore.ts";
import type { PlayStoreAppPlayStore } from "./PlayStoreAppPlayStore.ts";
import {
    PlayStoreAppPlayStoreFromJSON,
    PlayStoreAppPlayStoreFromJSONTyped,
    PlayStoreAppPlayStoreToJSON,
} from "./PlayStoreAppPlayStore.ts";

/**
 * 
 * @export
 * @interface App
 */
export interface App {
    /**
     * 
     * @type {AmazonAppAmazon}
     * @memberof App
     */
    amazon?: AmazonAppAmazon;
    /**
     * 
     * @type {AppStoreAppAppStore}
     * @memberof App
     */
    appStore?: AppStoreAppAppStore;
    /**
     * 
     * @type {MacAppStoreAppMacAppStore}
     * @memberof App
     */
    macAppStore?: MacAppStoreAppMacAppStore;
    /**
     * 
     * @type {PlayStoreAppPlayStore}
     * @memberof App
     */
    playStore?: PlayStoreAppPlayStore;
    /**
     * String representing the object's type. Objects of the same type share the same value.
     * @type {string}
     * @memberof App
     */
    object: AppObjectEnum;
    /**
     * The id of the app
     * @type {string}
     * @memberof App
     */
    id: string;
    /**
     * The name of the app
     * @type {string}
     * @memberof App
     */
    name: string;
    /**
     * The date when the app was created in ms since epoch
     * @type {number}
     * @memberof App
     */
    createdAt: number;
    /**
     * The platform of the app
     * @type {string}
     * @memberof App
     */
    type: AppTypeEnum;
    /**
     * The id of the project
     * @type {string}
     * @memberof App
     */
    projectId: string;
}


/**
 * @export
 */
export const AppObjectEnum = {
    App: 'app'
} as const;
export type AppObjectEnum = typeof AppObjectEnum[keyof typeof AppObjectEnum];

/**
 * @export
 */
export const AppTypeEnum = {
    Amazon: 'amazon',
    AppStore: 'app_store',
    MacAppStore: 'mac_app_store',
    PlayStore: 'play_store',
    Stripe: 'stripe'
} as const;
export type AppTypeEnum = typeof AppTypeEnum[keyof typeof AppTypeEnum];


/**
 * Check if a given object implements the App interface.
 */
export function instanceOfApp(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('type' in value)) return false;
    if (!('projectId' in value)) return false;
    return true;
}

export function AppFromJSON(json: any): App {
    return AppFromJSONTyped(json, false);
}

export function AppFromJSONTyped(json: any, ignoreDiscriminator: boolean): App {
    if (json == null) {
        return json;
    }
    return {
        
        'amazon': json['amazon'] == null ? undefined : AmazonAppAmazonFromJSON(json['amazon']),
        'appStore': json['app_store'] == null ? undefined : AppStoreAppAppStoreFromJSON(json['app_store']),
        'macAppStore': json['mac_app_store'] == null ? undefined : MacAppStoreAppMacAppStoreFromJSON(json['mac_app_store']),
        'playStore': json['play_store'] == null ? undefined : PlayStoreAppPlayStoreFromJSON(json['play_store']),
        'object': json['object'],
        'id': json['id'],
        'name': json['name'],
        'createdAt': json['created_at'],
        'type': json['type'],
        'projectId': json['project_id'],
    };
}

export function AppToJSON(value?: App | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amazon': AmazonAppAmazonToJSON(value['amazon']),
        'app_store': AppStoreAppAppStoreToJSON(value['appStore']),
        'mac_app_store': MacAppStoreAppMacAppStoreToJSON(value['macAppStore']),
        'play_store': PlayStoreAppPlayStoreToJSON(value['playStore']),
        'object': value['object'],
        'id': value['id'],
        'name': value['name'],
        'created_at': value['createdAt'],
        'type': value['type'],
        'project_id': value['projectId'],
    };
}

