/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppStoreAppAppStore } from './AppStoreAppAppStore';
import {
    AppStoreAppAppStoreFromJSON,
    AppStoreAppAppStoreFromJSONTyped,
    AppStoreAppAppStoreToJSON,
} from './AppStoreAppAppStore';

/**
 * 
 * @export
 * @interface AppStoreApp
 */
export interface AppStoreApp {
    /**
     * 
     * @type {AppStoreAppAppStore}
     * @memberof AppStoreApp
     */
    appStore?: AppStoreAppAppStore;
}

/**
 * Check if a given object implements the AppStoreApp interface.
 */
export function instanceOfAppStoreApp(value: object): boolean {
    return true;
}

export function AppStoreAppFromJSON(json: any): AppStoreApp {
    return AppStoreAppFromJSONTyped(json, false);
}

export function AppStoreAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreApp {
    if (json == null) {
        return json;
    }
    return {
        
        'appStore': json['app_store'] == null ? undefined : AppStoreAppAppStoreFromJSON(json['app_store']),
    };
}

export function AppStoreAppToJSON(value?: AppStoreApp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'app_store': AppStoreAppAppStoreToJSON(value['appStore']),
    };
}

