/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * App Store type details
 * @export
 * @interface AppStoreAppAppStore
 */
export interface AppStoreAppAppStore {
    /**
     * The bundle ID of the app
     * @type {string}
     * @memberof AppStoreAppAppStore
     */
    bundleId: string;
}

/**
 * Check if a given object implements the AppStoreAppAppStore interface.
 */
export function instanceOfAppStoreAppAppStore(value: object): boolean {
    if (!('bundleId' in value)) return false;
    return true;
}

export function AppStoreAppAppStoreFromJSON(json: any): AppStoreAppAppStore {
    return AppStoreAppAppStoreFromJSONTyped(json, false);
}

export function AppStoreAppAppStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreAppAppStore {
    if (json == null) {
        return json;
    }
    return {
        
        'bundleId': json['bundle_id'],
    };
}

export function AppStoreAppAppStoreToJSON(value?: AppStoreAppAppStore | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bundle_id': value['bundleId'],
    };
}

