/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * App Store type details. Should only be used when type is app_store.
 * @export
 * @interface AppStoreAppCreateAppStore
 */
export interface AppStoreAppCreateAppStore {
    /**
     * The bundle ID of the app
     * @type {string}
     * @memberof AppStoreAppCreateAppStore
     */
    bundleId: string;
    /**
     * The shared secret of the app
     * @type {string}
     * @memberof AppStoreAppCreateAppStore
     */
    sharedSecret?: string;
    /**
     * PKCS /#8 In App Key downloaded from App Store Connect in PEM format. Copy the contents
     * of the file in this field. See instructions on how to get it in: 
     * https://www.revenuecat.com/docs/in-app-purchase-key-configuration
     * 
     * @type {string}
     * @memberof AppStoreAppCreateAppStore
     */
    subscriptionPrivateKey: string;
    /**
     * In App Key id. The ID of the downloaded in app key. You can get it from App Store Connect
     * @type {string}
     * @memberof AppStoreAppCreateAppStore
     */
    subscriptionKeyId: string;
    /**
     * The key Issuer id. See instructions on how to obtain this in:
     * https://www.revenuecat.com/docs/in-app-purchase-key-configuration#3-providing-the-issuer-id-to-revenuecat
     * 
     * @type {string}
     * @memberof AppStoreAppCreateAppStore
     */
    subscriptionKeyIssuer: string;
}

/**
 * Check if a given object implements the AppStoreAppCreateAppStore interface.
 */
export function instanceOfAppStoreAppCreateAppStore(value: object): boolean {
    if (!('bundleId' in value)) return false;
    if (!('subscriptionPrivateKey' in value)) return false;
    if (!('subscriptionKeyId' in value)) return false;
    if (!('subscriptionKeyIssuer' in value)) return false;
    return true;
}

export function AppStoreAppCreateAppStoreFromJSON(json: any): AppStoreAppCreateAppStore {
    return AppStoreAppCreateAppStoreFromJSONTyped(json, false);
}

export function AppStoreAppCreateAppStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStoreAppCreateAppStore {
    if (json == null) {
        return json;
    }
    return {
        
        'bundleId': json['bundle_id'],
        'sharedSecret': json['shared_secret'] == null ? undefined : json['shared_secret'],
        'subscriptionPrivateKey': json['subscription_private_key'],
        'subscriptionKeyId': json['subscription_key_id'],
        'subscriptionKeyIssuer': json['subscription_key_issuer'],
    };
}

export function AppStoreAppCreateAppStoreToJSON(value?: AppStoreAppCreateAppStore | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bundle_id': value['bundleId'],
        'shared_secret': value['sharedSecret'],
        'subscription_private_key': value['subscriptionPrivateKey'],
        'subscription_key_id': value['subscriptionKeyId'],
        'subscription_key_issuer': value['subscriptionKeyIssuer'],
    };
}

