/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * 
 * @export
 * @interface AttachProductsToEntitlementRequest
 */
export interface AttachProductsToEntitlementRequest {
    /**
     * IDs of the products to be attached to the entitlement.
     * @type {Array<string>}
     * @memberof AttachProductsToEntitlementRequest
     */
    productIds: Array<string>;
}

/**
 * Check if a given object implements the AttachProductsToEntitlementRequest interface.
 */
export function instanceOfAttachProductsToEntitlementRequest(value: object): boolean {
    if (!('productIds' in value)) return false;
    return true;
}

export function AttachProductsToEntitlementRequestFromJSON(json: any): AttachProductsToEntitlementRequest {
    return AttachProductsToEntitlementRequestFromJSONTyped(json, false);
}

export function AttachProductsToEntitlementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachProductsToEntitlementRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productIds': json['product_ids'],
    };
}

export function AttachProductsToEntitlementRequestToJSON(value?: AttachProductsToEntitlementRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'product_ids': value['productIds'],
    };
}

