/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * 
 * @export
 * @interface CreateApp422Response
 */
export interface CreateApp422Response {
    /**
     * String representing the object's type. Objects of the same type share the same value.
     * @type {string}
     * @memberof CreateApp422Response
     */
    object: CreateApp422ResponseObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateApp422Response
     */
    type: CreateApp422ResponseTypeEnum;
    /**
     * If the error is parameter-specific, the parameter related to the error
     * @type {string}
     * @memberof CreateApp422Response
     */
    param?: string;
    /**
     * A URL to more information about the error reported
     * @type {string}
     * @memberof CreateApp422Response
     */
    docUrl?: string;
    /**
     * A message describing the reason of the error
     * @type {string}
     * @memberof CreateApp422Response
     */
    message: string;
    /**
     * Indicates if the error is retryable or not
     * @type {boolean}
     * @memberof CreateApp422Response
     */
    retryable: boolean;
    /**
     * The ms the client should wait before retrying the request. Only present for retryable errors.
     * @type {number}
     * @memberof CreateApp422Response
     */
    backoffMs?: number;
}


/**
 * @export
 */
export const CreateApp422ResponseObjectEnum = {
    Error: 'error'
} as const;
export type CreateApp422ResponseObjectEnum = typeof CreateApp422ResponseObjectEnum[keyof typeof CreateApp422ResponseObjectEnum];

/**
 * @export
 */
export const CreateApp422ResponseTypeEnum = {
    UnprocessableEntityError: 'unprocessable_entity_error',
    ParameterError: 'parameter_error',
    StoreError: 'store_error'
} as const;
export type CreateApp422ResponseTypeEnum = typeof CreateApp422ResponseTypeEnum[keyof typeof CreateApp422ResponseTypeEnum];


/**
 * Check if a given object implements the CreateApp422Response interface.
 */
export function instanceOfCreateApp422Response(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('type' in value)) return false;
    if (!('message' in value)) return false;
    if (!('retryable' in value)) return false;
    return true;
}

export function CreateApp422ResponseFromJSON(json: any): CreateApp422Response {
    return CreateApp422ResponseFromJSONTyped(json, false);
}

export function CreateApp422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApp422Response {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'type': json['type'],
        'param': json['param'] == null ? undefined : json['param'],
        'docUrl': json['doc_url'] == null ? undefined : json['doc_url'],
        'message': json['message'],
        'retryable': json['retryable'],
        'backoffMs': json['backoff_ms'] == null ? undefined : json['backoff_ms'],
    };
}

export function CreateApp422ResponseToJSON(value?: CreateApp422Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'type': value['type'],
        'param': value['param'],
        'doc_url': value['docUrl'],
        'message': value['message'],
        'retryable': value['retryable'],
        'backoff_ms': value['backoffMs'],
    };
}

