/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePackagesRequest
 */
export interface CreatePackagesRequest {
    /**
     * The lookup_key of the package
     * @type {string}
     * @memberof CreatePackagesRequest
     */
    lookupKey: string;
    /**
     * The display name of the package
     * @type {string}
     * @memberof CreatePackagesRequest
     */
    displayName: string;
    /**
     * The position of the package in the offering
     * @type {number}
     * @memberof CreatePackagesRequest
     */
    position?: number;
}

/**
 * Check if a given object implements the CreatePackagesRequest interface.
 */
export function instanceOfCreatePackagesRequest(value: object): boolean {
    if (!('lookupKey' in value)) return false;
    if (!('displayName' in value)) return false;
    return true;
}

export function CreatePackagesRequestFromJSON(json: any): CreatePackagesRequest {
    return CreatePackagesRequestFromJSONTyped(json, false);
}

export function CreatePackagesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePackagesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'lookupKey': json['lookup_key'],
        'displayName': json['display_name'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function CreatePackagesRequestToJSON(value?: CreatePackagesRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lookup_key': value['lookupKey'],
        'display_name': value['displayName'],
        'position': value['position'],
    };
}

