/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * 
 * @export
 * @interface DetachProductsFromEntitlementRequest
 */
export interface DetachProductsFromEntitlementRequest {
    /**
     * IDs of the products to be detached from the entitlement.
     * @type {Array<string>}
     * @memberof DetachProductsFromEntitlementRequest
     */
    productIds: Array<string>;
}

/**
 * Check if a given object implements the DetachProductsFromEntitlementRequest interface.
 */
export function instanceOfDetachProductsFromEntitlementRequest(value: object): boolean {
    if (!('productIds' in value)) return false;
    return true;
}

export function DetachProductsFromEntitlementRequestFromJSON(json: any): DetachProductsFromEntitlementRequest {
    return DetachProductsFromEntitlementRequestFromJSONTyped(json, false);
}

export function DetachProductsFromEntitlementRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetachProductsFromEntitlementRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productIds': json['product_ids'],
    };
}

export function DetachProductsFromEntitlementRequestToJSON(value?: DetachProductsFromEntitlementRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'product_ids': value['productIds'],
    };
}

