/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetachProductsFromPackageRequest
 */
export interface DetachProductsFromPackageRequest {
    /**
     * IDs of the products to detach from the package
     * @type {Array<string>}
     * @memberof DetachProductsFromPackageRequest
     */
    productIds: Array<string>;
}

/**
 * Check if a given object implements the DetachProductsFromPackageRequest interface.
 */
export function instanceOfDetachProductsFromPackageRequest(value: object): boolean {
    if (!('productIds' in value)) return false;
    return true;
}

export function DetachProductsFromPackageRequestFromJSON(json: any): DetachProductsFromPackageRequest {
    return DetachProductsFromPackageRequestFromJSONTyped(json, false);
}

export function DetachProductsFromPackageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetachProductsFromPackageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'productIds': json['product_ids'],
    };
}

export function DetachProductsFromPackageRequestToJSON(value?: DetachProductsFromPackageRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'product_ids': value['productIds'],
    };
}

