/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const EligibilityCriteria = {
    All: 'all',
    GoogleSdkLt6: 'google_sdk_lt_6',
    GoogleSdkGe6: 'google_sdk_ge_6'
} as const;
export type EligibilityCriteria = typeof EligibilityCriteria[keyof typeof EligibilityCriteria];


export function EligibilityCriteriaFromJSON(json: any): EligibilityCriteria {
    return EligibilityCriteriaFromJSONTyped(json, false);
}

export function EligibilityCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): EligibilityCriteria {
    return json as EligibilityCriteria;
}

export function EligibilityCriteriaToJSON(value?: EligibilityCriteria | null): any {
    return value as any;
}

