/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The store environment
 * @export
 */
export const Environment = {
    Production: 'production',
    Sandbox: 'sandbox'
} as const;
export type Environment = typeof Environment[keyof typeof Environment];


export function EnvironmentFromJSON(json: any): Environment {
    return EnvironmentFromJSONTyped(json, false);
}

export function EnvironmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Environment {
    return json as Environment;
}

export function EnvironmentToJSON(value?: Environment | null): any {
    return value as any;
}

