/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceLineItem } from './InvoiceLineItem';
import {
    InvoiceLineItemFromJSON,
    InvoiceLineItemFromJSONTyped,
    InvoiceLineItemToJSON,
} from './InvoiceLineItem';
import type { MonetaryAmount } from './MonetaryAmount';
import {
    MonetaryAmountFromJSON,
    MonetaryAmountFromJSONTyped,
    MonetaryAmountToJSON,
} from './MonetaryAmount';

/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * String representing the object's type. Objects of the same type share the same value.
     * @type {string}
     * @memberof Invoice
     */
    object: InvoiceObjectEnum;
    /**
     * The id of the invoice
     * @type {string}
     * @memberof Invoice
     */
    id: string;
    /**
     * 
     * @type {MonetaryAmount}
     * @memberof Invoice
     */
    totalAmount: MonetaryAmount;
    /**
     * List of line items that are part of the invoice. Each line item represents a product that was purchased.
     * @type {Array<InvoiceLineItem>}
     * @memberof Invoice
     */
    lineItems: Array<InvoiceLineItem>;
    /**
     * The date when the invoiced was issued in ms since epoch
     * @type {number}
     * @memberof Invoice
     */
    issuedAt: number;
    /**
     * The date when the invoiced was paid in ms since epoch
     * @type {number}
     * @memberof Invoice
     */
    paidAt: number | null;
    /**
     * URL to download the invoice pdf
     * @type {string}
     * @memberof Invoice
     */
    invoiceUrl: string | null;
}


/**
 * @export
 */
export const InvoiceObjectEnum = {
    Invoice: 'invoice'
} as const;
export type InvoiceObjectEnum = typeof InvoiceObjectEnum[keyof typeof InvoiceObjectEnum];


/**
 * Check if a given object implements the Invoice interface.
 */
export function instanceOfInvoice(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('id' in value)) return false;
    if (!('totalAmount' in value)) return false;
    if (!('lineItems' in value)) return false;
    if (!('issuedAt' in value)) return false;
    if (!('paidAt' in value)) return false;
    if (!('invoiceUrl' in value)) return false;
    return true;
}

export function InvoiceFromJSON(json: any): Invoice {
    return InvoiceFromJSONTyped(json, false);
}

export function InvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invoice {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'id': json['id'],
        'totalAmount': MonetaryAmountFromJSON(json['total_amount']),
        'lineItems': ((json['line_items'] as Array<any>).map(InvoiceLineItemFromJSON)),
        'issuedAt': json['issued_at'],
        'paidAt': json['paid_at'],
        'invoiceUrl': json['invoice_url'],
    };
}

export function InvoiceToJSON(value?: Invoice | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'id': value['id'],
        'total_amount': MonetaryAmountToJSON(value['totalAmount']),
        'line_items': ((value['lineItems'] as Array<any>).map(InvoiceLineItemToJSON)),
        'issued_at': value['issuedAt'],
        'paid_at': value['paidAt'],
        'invoice_url': value['invoiceUrl'],
    };
}

