/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MonetaryAmount } from './MonetaryAmount';
import {
    MonetaryAmountFromJSON,
    MonetaryAmountFromJSONTyped,
    MonetaryAmountToJSON,
} from './MonetaryAmount';

/**
 * 
 * @export
 * @interface InvoiceLineItem
 */
export interface InvoiceLineItem {
    /**
     * String representing the object's type. Objects of the same type share the same value.
     * @type {string}
     * @memberof InvoiceLineItem
     */
    object: InvoiceLineItemObjectEnum;
    /**
     * The product identifier
     * @type {string}
     * @memberof InvoiceLineItem
     */
    productIdentifier: string;
    /**
     * The display name of the product
     * @type {string}
     * @memberof InvoiceLineItem
     */
    productDisplayName: string | null;
    /**
     * The duration of the subscription in ISO-8601 standard
     * @type {string}
     * @memberof InvoiceLineItem
     */
    productDuration: string | null;
    /**
     * Total purchased items
     * @type {number}
     * @memberof InvoiceLineItem
     */
    quantity: number;
    /**
     * 
     * @type {MonetaryAmount}
     * @memberof InvoiceLineItem
     */
    unitAmount: MonetaryAmount;
}


/**
 * @export
 */
export const InvoiceLineItemObjectEnum = {
    InvoiceLineItem: 'invoice.line_item'
} as const;
export type InvoiceLineItemObjectEnum = typeof InvoiceLineItemObjectEnum[keyof typeof InvoiceLineItemObjectEnum];


/**
 * Check if a given object implements the InvoiceLineItem interface.
 */
export function instanceOfInvoiceLineItem(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('productIdentifier' in value)) return false;
    if (!('productDisplayName' in value)) return false;
    if (!('productDuration' in value)) return false;
    if (!('quantity' in value)) return false;
    if (!('unitAmount' in value)) return false;
    return true;
}

export function InvoiceLineItemFromJSON(json: any): InvoiceLineItem {
    return InvoiceLineItemFromJSONTyped(json, false);
}

export function InvoiceLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceLineItem {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'productIdentifier': json['product_identifier'],
        'productDisplayName': json['product_display_name'],
        'productDuration': json['product_duration'],
        'quantity': json['quantity'],
        'unitAmount': MonetaryAmountFromJSON(json['unit_amount']),
    };
}

export function InvoiceLineItemToJSON(value?: InvoiceLineItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'product_identifier': value['productIdentifier'],
        'product_display_name': value['productDisplayName'],
        'product_duration': value['productDuration'],
        'quantity': value['quantity'],
        'unit_amount': MonetaryAmountToJSON(value['unitAmount']),
    };
}

