/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
import type { Package } from "./Package.ts";
import {
    PackageFromJSON,
    PackageFromJSONTyped,
    PackageToJSON,
} from "./Package.ts";

/**
 * 
 * @export
 * @interface ListPackages
 */
export interface ListPackages {
    /**
     * String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
     * @type {string}
     * @memberof ListPackages
     */
    object: ListPackagesObjectEnum;
    /**
     * Details about each object.
     * @type {Array<Package>}
     * @memberof ListPackages
     */
    items: Array<Package>;
    /**
     * URL to access the next page of the project's packages. If not present / null, there is no next page
     * @type {string}
     * @memberof ListPackages
     */
    nextPage: string | null;
    /**
     * The URL where this list can be accessed.
     * @type {string}
     * @memberof ListPackages
     */
    url: string;
}


/**
 * @export
 */
export const ListPackagesObjectEnum = {
    List: 'list'
} as const;
export type ListPackagesObjectEnum = typeof ListPackagesObjectEnum[keyof typeof ListPackagesObjectEnum];


/**
 * Check if a given object implements the ListPackages interface.
 */
export function instanceOfListPackages(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('items' in value)) return false;
    if (!('nextPage' in value)) return false;
    if (!('url' in value)) return false;
    return true;
}

export function ListPackagesFromJSON(json: any): ListPackages {
    return ListPackagesFromJSONTyped(json, false);
}

export function ListPackagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPackages {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'items': ((json['items'] as Array<any>).map(PackageFromJSON)),
        'nextPage': json['next_page'],
        'url': json['url'],
    };
}

export function ListPackagesToJSON(value?: ListPackages | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'items': ((value['items'] as Array<any>).map(PackageToJSON)),
        'next_page': value['nextPage'],
        'url': value['url'],
    };
}

