/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Offering } from './Offering';
import {
    OfferingFromJSON,
    OfferingFromJSONTyped,
    OfferingToJSON,
} from './Offering';

/**
 * 
 * @export
 * @interface ListOfferings
 */
export interface ListOfferings {
    /**
     * String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
     * @type {string}
     * @memberof ListOfferings
     */
    object: ListOfferingsObjectEnum;
    /**
     * Details about each object.
     * @type {Array<Offering>}
     * @memberof ListOfferings
     */
    items: Array<Offering>;
    /**
     * URL to access the next page of the project's offerings. If not present / null, there is no next page
     * @type {string}
     * @memberof ListOfferings
     */
    nextPage: string | null;
    /**
     * The URL where this list can be accessed.
     * @type {string}
     * @memberof ListOfferings
     */
    url: string;
}


/**
 * @export
 */
export const ListOfferingsObjectEnum = {
    List: 'list'
} as const;
export type ListOfferingsObjectEnum = typeof ListOfferingsObjectEnum[keyof typeof ListOfferingsObjectEnum];


/**
 * Check if a given object implements the ListOfferings interface.
 */
export function instanceOfListOfferings(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('items' in value)) return false;
    if (!('nextPage' in value)) return false;
    if (!('url' in value)) return false;
    return true;
}

export function ListOfferingsFromJSON(json: any): ListOfferings {
    return ListOfferingsFromJSONTyped(json, false);
}

export function ListOfferingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOfferings {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'items': ((json['items'] as Array<any>).map(OfferingFromJSON)),
        'nextPage': json['next_page'],
        'url': json['url'],
    };
}

export function ListOfferingsToJSON(value?: ListOfferings | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'items': ((value['items'] as Array<any>).map(OfferingToJSON)),
        'next_page': value['nextPage'],
        'url': value['url'],
    };
}

