/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListProjects404Response
 */
export interface ListProjects404Response {
    /**
     * String representing the object's type. Objects of the same type share the same value.
     * @type {string}
     * @memberof ListProjects404Response
     */
    object: ListProjects404ResponseObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof ListProjects404Response
     */
    type: ListProjects404ResponseTypeEnum;
    /**
     * If the error is parameter-specific, the parameter related to the error
     * @type {string}
     * @memberof ListProjects404Response
     */
    param?: string;
    /**
     * A URL to more information about the error reported
     * @type {string}
     * @memberof ListProjects404Response
     */
    docUrl?: string;
    /**
     * A message describing the reason of the error
     * @type {string}
     * @memberof ListProjects404Response
     */
    message: string;
    /**
     * Indicates if the error is retryable or not
     * @type {boolean}
     * @memberof ListProjects404Response
     */
    retryable: boolean;
    /**
     * The ms the client should wait before retrying the request. Only present for retryable errors.
     * @type {number}
     * @memberof ListProjects404Response
     */
    backoffMs?: number;
}


/**
 * @export
 */
export const ListProjects404ResponseObjectEnum = {
    Error: 'error'
} as const;
export type ListProjects404ResponseObjectEnum = typeof ListProjects404ResponseObjectEnum[keyof typeof ListProjects404ResponseObjectEnum];

/**
 * @export
 */
export const ListProjects404ResponseTypeEnum = {
    ResourceMissing: 'resource_missing'
} as const;
export type ListProjects404ResponseTypeEnum = typeof ListProjects404ResponseTypeEnum[keyof typeof ListProjects404ResponseTypeEnum];


/**
 * Check if a given object implements the ListProjects404Response interface.
 */
export function instanceOfListProjects404Response(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('type' in value)) return false;
    if (!('message' in value)) return false;
    if (!('retryable' in value)) return false;
    return true;
}

export function ListProjects404ResponseFromJSON(json: any): ListProjects404Response {
    return ListProjects404ResponseFromJSONTyped(json, false);
}

export function ListProjects404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProjects404Response {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'type': json['type'],
        'param': json['param'] == null ? undefined : json['param'],
        'docUrl': json['doc_url'] == null ? undefined : json['doc_url'],
        'message': json['message'],
        'retryable': json['retryable'],
        'backoffMs': json['backoff_ms'] == null ? undefined : json['backoff_ms'],
    };
}

export function ListProjects404ResponseToJSON(value?: ListProjects404Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'type': value['type'],
        'param': value['param'],
        'doc_url': value['docUrl'],
        'message': value['message'],
        'retryable': value['retryable'],
        'backoff_ms': value['backoffMs'],
    };
}

