/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * 
 * @export
 * @interface ListProjects400Response
 */
export interface ListProjects400Response {
    /**
     * String representing the object's type. Objects of the same type share the same value.
     * @type {string}
     * @memberof ListProjects400Response
     */
    object: ListProjects400ResponseObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof ListProjects400Response
     */
    type: ListProjects400ResponseTypeEnum;
    /**
     * If the error is parameter-specific, the parameter related to the error
     * @type {string}
     * @memberof ListProjects400Response
     */
    param?: string;
    /**
     * A URL to more information about the error reported
     * @type {string}
     * @memberof ListProjects400Response
     */
    docUrl?: string;
    /**
     * A message describing the reason of the error
     * @type {string}
     * @memberof ListProjects400Response
     */
    message: string;
    /**
     * Indicates if the error is retryable or not
     * @type {boolean}
     * @memberof ListProjects400Response
     */
    retryable: boolean;
    /**
     * The ms the client should wait before retrying the request. Only present for retryable errors.
     * @type {number}
     * @memberof ListProjects400Response
     */
    backoffMs?: number;
}


/**
 * @export
 */
export const ListProjects400ResponseObjectEnum = {
    Error: 'error'
} as const;
export type ListProjects400ResponseObjectEnum = typeof ListProjects400ResponseObjectEnum[keyof typeof ListProjects400ResponseObjectEnum];

/**
 * @export
 */
export const ListProjects400ResponseTypeEnum = {
    ParameterError: 'parameter_error',
    InvalidRequest: 'invalid_request'
} as const;
export type ListProjects400ResponseTypeEnum = typeof ListProjects400ResponseTypeEnum[keyof typeof ListProjects400ResponseTypeEnum];


/**
 * Check if a given object implements the ListProjects400Response interface.
 */
export function instanceOfListProjects400Response(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('type' in value)) return false;
    if (!('message' in value)) return false;
    if (!('retryable' in value)) return false;
    return true;
}

export function ListProjects400ResponseFromJSON(json: any): ListProjects400Response {
    return ListProjects400ResponseFromJSONTyped(json, false);
}

export function ListProjects400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProjects400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'type': json['type'],
        'param': json['param'] == null ? undefined : json['param'],
        'docUrl': json['doc_url'] == null ? undefined : json['doc_url'],
        'message': json['message'],
        'retryable': json['retryable'],
        'backoffMs': json['backoff_ms'] == null ? undefined : json['backoff_ms'],
    };
}

export function ListProjects400ResponseToJSON(value?: ListProjects400Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'type': value['type'],
        'param': value['param'],
        'doc_url': value['docUrl'],
        'message': value['message'],
        'retryable': value['retryable'],
        'backoff_ms': value['backoffMs'],
    };
}

