/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface ListProducts
 */
export interface ListProducts {
    /**
     * String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
     * @type {string}
     * @memberof ListProducts
     */
    object: ListProductsObjectEnum;
    /**
     * Details about each object.
     * @type {Array<Product>}
     * @memberof ListProducts
     */
    items: Array<Product>;
    /**
     * URL to access the next page of the project's products. If not present / null, there is no next page
     * @type {string}
     * @memberof ListProducts
     */
    nextPage: string | null;
    /**
     * The URL where this list can be accessed.
     * @type {string}
     * @memberof ListProducts
     */
    url: string;
}


/**
 * @export
 */
export const ListProductsObjectEnum = {
    List: 'list'
} as const;
export type ListProductsObjectEnum = typeof ListProductsObjectEnum[keyof typeof ListProductsObjectEnum];


/**
 * Check if a given object implements the ListProducts interface.
 */
export function instanceOfListProducts(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('items' in value)) return false;
    if (!('nextPage' in value)) return false;
    if (!('url' in value)) return false;
    return true;
}

export function ListProductsFromJSON(json: any): ListProducts {
    return ListProductsFromJSONTyped(json, false);
}

export function ListProductsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProducts {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'items': ((json['items'] as Array<any>).map(ProductFromJSON)),
        'nextPage': json['next_page'],
        'url': json['url'],
    };
}

export function ListProductsToJSON(value?: ListProducts | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'items': ((value['items'] as Array<any>).map(ProductToJSON)),
        'next_page': value['nextPage'],
        'url': value['url'],
    };
}

