/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Project } from './Project';
import {
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
} from './Project';

/**
 * 
 * @export
 * @interface ListProjects
 */
export interface ListProjects {
    /**
     * String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
     * @type {string}
     * @memberof ListProjects
     */
    object: ListProjectsObjectEnum;
    /**
     * Details about each object.
     * @type {Array<Project>}
     * @memberof ListProjects
     */
    items: Array<Project>;
    /**
     * URL to access the next page of the projects. If not present / null, there is no next page
     * @type {string}
     * @memberof ListProjects
     */
    nextPage: string | null;
    /**
     * The URL where this list can be accessed.
     * @type {string}
     * @memberof ListProjects
     */
    url: string;
}


/**
 * @export
 */
export const ListProjectsObjectEnum = {
    List: 'list'
} as const;
export type ListProjectsObjectEnum = typeof ListProjectsObjectEnum[keyof typeof ListProjectsObjectEnum];


/**
 * Check if a given object implements the ListProjects interface.
 */
export function instanceOfListProjects(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('items' in value)) return false;
    if (!('nextPage' in value)) return false;
    if (!('url' in value)) return false;
    return true;
}

export function ListProjectsFromJSON(json: any): ListProjects {
    return ListProjectsFromJSONTyped(json, false);
}

export function ListProjectsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProjects {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'items': ((json['items'] as Array<any>).map(ProjectFromJSON)),
        'nextPage': json['next_page'],
        'url': json['url'],
    };
}

export function ListProjectsToJSON(value?: ListProjects | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'items': ((value['items'] as Array<any>).map(ProjectToJSON)),
        'next_page': value['nextPage'],
        'url': value['url'],
    };
}

