/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * 
 * @export
 * @interface ListProjects401Response
 */
export interface ListProjects401Response {
    /**
     * String representing the object's type. Objects of the same type share the same value.
     * @type {string}
     * @memberof ListProjects401Response
     */
    object: ListProjects401ResponseObjectEnum;
    /**
     * 
     * @type {string}
     * @memberof ListProjects401Response
     */
    type: ListProjects401ResponseTypeEnum;
    /**
     * If the error is parameter-specific, the parameter related to the error
     * @type {string}
     * @memberof ListProjects401Response
     */
    param?: string;
    /**
     * A URL to more information about the error reported
     * @type {string}
     * @memberof ListProjects401Response
     */
    docUrl?: string;
    /**
     * A message describing the reason of the error
     * @type {string}
     * @memberof ListProjects401Response
     */
    message: string;
    /**
     * Indicates if the error is retryable or not
     * @type {boolean}
     * @memberof ListProjects401Response
     */
    retryable: boolean;
    /**
     * The ms the client should wait before retrying the request. Only present for retryable errors.
     * @type {number}
     * @memberof ListProjects401Response
     */
    backoffMs?: number;
}


/**
 * @export
 */
export const ListProjects401ResponseObjectEnum = {
    Error: 'error'
} as const;
export type ListProjects401ResponseObjectEnum = typeof ListProjects401ResponseObjectEnum[keyof typeof ListProjects401ResponseObjectEnum];

/**
 * @export
 */
export const ListProjects401ResponseTypeEnum = {
    AuthenticationError: 'authentication_error'
} as const;
export type ListProjects401ResponseTypeEnum = typeof ListProjects401ResponseTypeEnum[keyof typeof ListProjects401ResponseTypeEnum];


/**
 * Check if a given object implements the ListProjects401Response interface.
 */
export function instanceOfListProjects401Response(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('type' in value)) return false;
    if (!('message' in value)) return false;
    if (!('retryable' in value)) return false;
    return true;
}

export function ListProjects401ResponseFromJSON(json: any): ListProjects401Response {
    return ListProjects401ResponseFromJSONTyped(json, false);
}

export function ListProjects401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProjects401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'type': json['type'],
        'param': json['param'] == null ? undefined : json['param'],
        'docUrl': json['doc_url'] == null ? undefined : json['doc_url'],
        'message': json['message'],
        'retryable': json['retryable'],
        'backoffMs': json['backoff_ms'] == null ? undefined : json['backoff_ms'],
    };
}

export function ListProjects401ResponseToJSON(value?: ListProjects401Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'type': value['type'],
        'param': value['param'],
        'doc_url': value['docUrl'],
        'message': value['message'],
        'retryable': value['retryable'],
        'backoff_ms': value['backoffMs'],
    };
}

