/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
import type { MacAppStoreAppMacAppStore } from "./MacAppStoreAppMacAppStore.ts";
import {
    MacAppStoreAppMacAppStoreFromJSON,
    MacAppStoreAppMacAppStoreFromJSONTyped,
    MacAppStoreAppMacAppStoreToJSON,
} from "./MacAppStoreAppMacAppStore.ts";

/**
 * 
 * @export
 * @interface MacAppStoreApp
 */
export interface MacAppStoreApp {
    /**
     * 
     * @type {MacAppStoreAppMacAppStore}
     * @memberof MacAppStoreApp
     */
    macAppStore?: MacAppStoreAppMacAppStore;
}

/**
 * Check if a given object implements the MacAppStoreApp interface.
 */
export function instanceOfMacAppStoreApp(value: object): boolean {
    return true;
}

export function MacAppStoreAppFromJSON(json: any): MacAppStoreApp {
    return MacAppStoreAppFromJSONTyped(json, false);
}

export function MacAppStoreAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): MacAppStoreApp {
    if (json == null) {
        return json;
    }
    return {
        
        'macAppStore': json['mac_app_store'] == null ? undefined : MacAppStoreAppMacAppStoreFromJSON(json['mac_app_store']),
    };
}

export function MacAppStoreAppToJSON(value?: MacAppStoreApp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mac_app_store': MacAppStoreAppMacAppStoreToJSON(value['macAppStore']),
    };
}

