/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * Mac App Store type details. Should only be used when type is mac_app_store.
 * @export
 * @interface MacAppStoreAppCreateMacAppStore
 */
export interface MacAppStoreAppCreateMacAppStore {
    /**
     * The bundle ID of the app
     * @type {string}
     * @memberof MacAppStoreAppCreateMacAppStore
     */
    bundleId: string;
    /**
     * The shared secret of the app
     * @type {string}
     * @memberof MacAppStoreAppCreateMacAppStore
     */
    sharedSecret?: string;
}

/**
 * Check if a given object implements the MacAppStoreAppCreateMacAppStore interface.
 */
export function instanceOfMacAppStoreAppCreateMacAppStore(value: object): boolean {
    if (!('bundleId' in value)) return false;
    return true;
}

export function MacAppStoreAppCreateMacAppStoreFromJSON(json: any): MacAppStoreAppCreateMacAppStore {
    return MacAppStoreAppCreateMacAppStoreFromJSONTyped(json, false);
}

export function MacAppStoreAppCreateMacAppStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): MacAppStoreAppCreateMacAppStore {
    if (json == null) {
        return json;
    }
    return {
        
        'bundleId': json['bundle_id'],
        'sharedSecret': json['shared_secret'] == null ? undefined : json['shared_secret'],
    };
}

export function MacAppStoreAppCreateMacAppStoreToJSON(value?: MacAppStoreAppCreateMacAppStore | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bundle_id': value['bundleId'],
        'shared_secret': value['sharedSecret'],
    };
}

