/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MacAppStoreAppCreateMacAppStore } from './MacAppStoreAppCreateMacAppStore';
import {
    MacAppStoreAppCreateMacAppStoreFromJSON,
    MacAppStoreAppCreateMacAppStoreFromJSONTyped,
    MacAppStoreAppCreateMacAppStoreToJSON,
} from './MacAppStoreAppCreateMacAppStore';

/**
 * 
 * @export
 * @interface MacAppStoreAppCreate
 */
export interface MacAppStoreAppCreate {
    /**
     * 
     * @type {MacAppStoreAppCreateMacAppStore}
     * @memberof MacAppStoreAppCreate
     */
    macAppStore?: MacAppStoreAppCreateMacAppStore;
}

/**
 * Check if a given object implements the MacAppStoreAppCreate interface.
 */
export function instanceOfMacAppStoreAppCreate(value: object): boolean {
    return true;
}

export function MacAppStoreAppCreateFromJSON(json: any): MacAppStoreAppCreate {
    return MacAppStoreAppCreateFromJSONTyped(json, false);
}

export function MacAppStoreAppCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): MacAppStoreAppCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'macAppStore': json['mac_app_store'] == null ? undefined : MacAppStoreAppCreateMacAppStoreFromJSON(json['mac_app_store']),
    };
}

export function MacAppStoreAppCreateToJSON(value?: MacAppStoreAppCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mac_app_store': MacAppStoreAppCreateMacAppStoreToJSON(value['macAppStore']),
    };
}

