/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * Legacy Mac App Store type details
 * @export
 * @interface MacAppStoreAppMacAppStore
 */
export interface MacAppStoreAppMacAppStore {
    /**
     * The bundle ID of the app
     * @type {string}
     * @memberof MacAppStoreAppMacAppStore
     */
    bundleId: string;
}

/**
 * Check if a given object implements the MacAppStoreAppMacAppStore interface.
 */
export function instanceOfMacAppStoreAppMacAppStore(value: object): boolean {
    if (!('bundleId' in value)) return false;
    return true;
}

export function MacAppStoreAppMacAppStoreFromJSON(json: any): MacAppStoreAppMacAppStore {
    return MacAppStoreAppMacAppStoreFromJSONTyped(json, false);
}

export function MacAppStoreAppMacAppStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): MacAppStoreAppMacAppStore {
    if (json == null) {
        return json;
    }
    return {
        
        'bundleId': json['bundle_id'],
    };
}

export function MacAppStoreAppMacAppStoreToJSON(value?: MacAppStoreAppMacAppStore | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bundle_id': value['bundleId'],
    };
}

