/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Ownership = {
    Purchased: 'purchased',
    FamilyShared: 'family_shared'
} as const;
export type Ownership = typeof Ownership[keyof typeof Ownership];


export function OwnershipFromJSON(json: any): Ownership {
    return OwnershipFromJSONTyped(json, false);
}

export function OwnershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ownership {
    return json as Ownership;
}

export function OwnershipToJSON(value?: Ownership | null): any {
    return value as any;
}

