/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EligibilityCriteria } from './EligibilityCriteria';
import {
    EligibilityCriteriaFromJSON,
    EligibilityCriteriaFromJSONTyped,
    EligibilityCriteriaToJSON,
} from './EligibilityCriteria';

/**
 * 
 * @export
 * @interface PackageProductIDAssociation
 */
export interface PackageProductIDAssociation {
    /**
     * 
     * @type {string}
     * @memberof PackageProductIDAssociation
     */
    productId: string;
    /**
     * 
     * @type {EligibilityCriteria}
     * @memberof PackageProductIDAssociation
     */
    eligibilityCriteria: EligibilityCriteria;
}

/**
 * Check if a given object implements the PackageProductIDAssociation interface.
 */
export function instanceOfPackageProductIDAssociation(value: object): boolean {
    if (!('productId' in value)) return false;
    if (!('eligibilityCriteria' in value)) return false;
    return true;
}

export function PackageProductIDAssociationFromJSON(json: any): PackageProductIDAssociation {
    return PackageProductIDAssociationFromJSONTyped(json, false);
}

export function PackageProductIDAssociationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PackageProductIDAssociation {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['product_id'],
        'eligibilityCriteria': EligibilityCriteriaFromJSON(json['eligibility_criteria']),
    };
}

export function PackageProductIDAssociationToJSON(value?: PackageProductIDAssociation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'product_id': value['productId'],
        'eligibility_criteria': EligibilityCriteriaToJSON(value['eligibilityCriteria']),
    };
}

