/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayStoreAppPlayStore } from './PlayStoreAppPlayStore';
import {
    PlayStoreAppPlayStoreFromJSON,
    PlayStoreAppPlayStoreFromJSONTyped,
    PlayStoreAppPlayStoreToJSON,
} from './PlayStoreAppPlayStore';

/**
 * 
 * @export
 * @interface PlayStoreApp
 */
export interface PlayStoreApp {
    /**
     * 
     * @type {PlayStoreAppPlayStore}
     * @memberof PlayStoreApp
     */
    playStore?: PlayStoreAppPlayStore;
}

/**
 * Check if a given object implements the PlayStoreApp interface.
 */
export function instanceOfPlayStoreApp(value: object): boolean {
    return true;
}

export function PlayStoreAppFromJSON(json: any): PlayStoreApp {
    return PlayStoreAppFromJSONTyped(json, false);
}

export function PlayStoreAppFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayStoreApp {
    if (json == null) {
        return json;
    }
    return {
        
        'playStore': json['play_store'] == null ? undefined : PlayStoreAppPlayStoreFromJSON(json['play_store']),
    };
}

export function PlayStoreAppToJSON(value?: PlayStoreApp | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'play_store': PlayStoreAppPlayStoreToJSON(value['playStore']),
    };
}

