/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * Play Store type details
 * @export
 * @interface PlayStoreAppPlayStore
 */
export interface PlayStoreAppPlayStore {
    /**
     * The package name of the app
     * @type {string}
     * @memberof PlayStoreAppPlayStore
     */
    packageName: string;
}

/**
 * Check if a given object implements the PlayStoreAppPlayStore interface.
 */
export function instanceOfPlayStoreAppPlayStore(value: object): boolean {
    if (!('packageName' in value)) return false;
    return true;
}

export function PlayStoreAppPlayStoreFromJSON(json: any): PlayStoreAppPlayStore {
    return PlayStoreAppPlayStoreFromJSONTyped(json, false);
}

export function PlayStoreAppPlayStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayStoreAppPlayStore {
    if (json == null) {
        return json;
    }
    return {
        
        'packageName': json['package_name'],
    };
}

export function PlayStoreAppPlayStoreToJSON(value?: PlayStoreAppPlayStore | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'package_name': value['packageName'],
    };
}

