/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
import type { UpdateAppRequestPlayStore } from "./UpdateAppRequestPlayStore.ts";
import {
    UpdateAppRequestPlayStoreFromJSON,
    UpdateAppRequestPlayStoreFromJSONTyped,
    UpdateAppRequestPlayStoreToJSON,
} from "./UpdateAppRequestPlayStore.ts";

/**
 * 
 * @export
 * @interface PlayStoreAppCreate
 */
export interface PlayStoreAppCreate {
    /**
     * 
     * @type {UpdateAppRequestPlayStore}
     * @memberof PlayStoreAppCreate
     */
    playStore?: UpdateAppRequestPlayStore;
}

/**
 * Check if a given object implements the PlayStoreAppCreate interface.
 */
export function instanceOfPlayStoreAppCreate(value: object): boolean {
    return true;
}

export function PlayStoreAppCreateFromJSON(json: any): PlayStoreAppCreate {
    return PlayStoreAppCreateFromJSONTyped(json, false);
}

export function PlayStoreAppCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayStoreAppCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'playStore': json['play_store'] == null ? undefined : UpdateAppRequestPlayStoreFromJSON(json['play_store']),
    };
}

export function PlayStoreAppCreateToJSON(value?: PlayStoreAppCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'play_store': UpdateAppRequestPlayStoreToJSON(value['playStore']),
    };
}

