/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface ProductsFromEntitlement
 */
export interface ProductsFromEntitlement {
    /**
     * String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
     * @type {string}
     * @memberof ProductsFromEntitlement
     */
    object: ProductsFromEntitlementObjectEnum;
    /**
     * Details about each object.
     * @type {Array<Product>}
     * @memberof ProductsFromEntitlement
     */
    items: Array<Product>;
    /**
     * URL to access the next page of the entitlement's products. If not present / null, there is no next page
     * @type {string}
     * @memberof ProductsFromEntitlement
     */
    nextPage: string | null;
    /**
     * The URL where this list can be accessed.
     * @type {string}
     * @memberof ProductsFromEntitlement
     */
    url: string;
}


/**
 * @export
 */
export const ProductsFromEntitlementObjectEnum = {
    List: 'list'
} as const;
export type ProductsFromEntitlementObjectEnum = typeof ProductsFromEntitlementObjectEnum[keyof typeof ProductsFromEntitlementObjectEnum];


/**
 * Check if a given object implements the ProductsFromEntitlement interface.
 */
export function instanceOfProductsFromEntitlement(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('items' in value)) return false;
    if (!('nextPage' in value)) return false;
    if (!('url' in value)) return false;
    return true;
}

export function ProductsFromEntitlementFromJSON(json: any): ProductsFromEntitlement {
    return ProductsFromEntitlementFromJSONTyped(json, false);
}

export function ProductsFromEntitlementFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsFromEntitlement {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'items': ((json['items'] as Array<any>).map(ProductFromJSON)),
        'nextPage': json['next_page'],
        'url': json['url'],
    };
}

export function ProductsFromEntitlementToJSON(value?: ProductsFromEntitlement | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'items': ((value['items'] as Array<any>).map(ProductToJSON)),
        'next_page': value['nextPage'],
        'url': value['url'],
    };
}

