/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { App } from './App';
import {
    AppFromJSON,
    AppFromJSONTyped,
    AppToJSON,
} from './App';
import type { ProductType } from './ProductType';
import {
    ProductTypeFromJSON,
    ProductTypeFromJSONTyped,
    ProductTypeToJSON,
} from './ProductType';
import type { SubscriptionProduct } from './SubscriptionProduct';
import {
    SubscriptionProductFromJSON,
    SubscriptionProductFromJSONTyped,
    SubscriptionProductToJSON,
} from './SubscriptionProduct';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * String representing the object's type. Objects of the same type share the same value. Always has the value `list`.
     * @type {string}
     * @memberof Product
     */
    object: ProductObjectEnum;
    /**
     * The id of the product
     * @type {string}
     * @memberof Product
     */
    id: string;
    /**
     * The store product identifier
     * @type {string}
     * @memberof Product
     */
    storeIdentifier: string;
    /**
     * 
     * @type {ProductType}
     * @memberof Product
     */
    type: ProductType;
    /**
     * 
     * @type {SubscriptionProduct}
     * @memberof Product
     */
    subscription?: SubscriptionProduct;
    /**
     * The date when the product was created in ms since epoch
     * @type {number}
     * @memberof Product
     */
    createdAt: number;
    /**
     * The id of the app
     * @type {string}
     * @memberof Product
     */
    appId: string;
    /**
     * 
     * @type {App}
     * @memberof Product
     */
    app?: App;
    /**
     * The display name of the product
     * @type {string}
     * @memberof Product
     */
    displayName: string | null;
}


/**
 * @export
 */
export const ProductObjectEnum = {
    Product: 'product'
} as const;
export type ProductObjectEnum = typeof ProductObjectEnum[keyof typeof ProductObjectEnum];


/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('id' in value)) return false;
    if (!('storeIdentifier' in value)) return false;
    if (!('type' in value)) return false;
    if (!('createdAt' in value)) return false;
    if (!('appId' in value)) return false;
    if (!('displayName' in value)) return false;
    return true;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'id': json['id'],
        'storeIdentifier': json['store_identifier'],
        'type': ProductTypeFromJSON(json['type']),
        'subscription': json['subscription'] == null ? undefined : SubscriptionProductFromJSON(json['subscription']),
        'createdAt': json['created_at'],
        'appId': json['app_id'],
        'app': json['app'] == null ? undefined : AppFromJSON(json['app']),
        'displayName': json['display_name'],
    };
}

export function ProductToJSON(value?: Product | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'id': value['id'],
        'store_identifier': value['storeIdentifier'],
        'type': ProductTypeToJSON(value['type']),
        'subscription': SubscriptionProductToJSON(value['subscription']),
        'created_at': value['createdAt'],
        'app_id': value['appId'],
        'app': AppToJSON(value['app']),
        'display_name': value['displayName'],
    };
}

