/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * String representing the object's type. Objects of the same type share the same value.
     * @type {string}
     * @memberof Project
     */
    object: ProjectObjectEnum;
    /**
     * The id of the project
     * @type {string}
     * @memberof Project
     */
    id: string;
    /**
     * The name of the project
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     * The date when the project was created in ms since epoch
     * @type {number}
     * @memberof Project
     */
    createdAt: number;
}


/**
 * @export
 */
export const ProjectObjectEnum = {
    Project: 'project'
} as const;
export type ProjectObjectEnum = typeof ProjectObjectEnum[keyof typeof ProjectObjectEnum];


/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): boolean {
    if (!('object' in value)) return false;
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('createdAt' in value)) return false;
    return true;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'id': json['id'],
        'name': json['name'],
        'createdAt': json['created_at'],
    };
}

export function ProjectToJSON(value?: Project | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'object': value['object'],
        'id': value['id'],
        'name': value['name'],
        'created_at': value['createdAt'],
    };
}

