/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * 
 * @export
 * @interface SubscriptionProduct
 */
export interface SubscriptionProduct {
    /**
     * The duration of the subscription in ISO-8601 standard
     * @type {string}
     * @memberof SubscriptionProduct
     */
    duration: string | null;
    /**
     * The duration of the subscription's grace period in ISO-8601 standard
     * @type {string}
     * @memberof SubscriptionProduct
     */
    gracePeriodDuration: string | null;
    /**
     * The duration of the subcription's trial period in ISO-8601 standard
     * @type {string}
     * @memberof SubscriptionProduct
     */
    trialDuration: string | null;
}

/**
 * Check if a given object implements the SubscriptionProduct interface.
 */
export function instanceOfSubscriptionProduct(value: object): boolean {
    if (!('duration' in value)) return false;
    if (!('gracePeriodDuration' in value)) return false;
    if (!('trialDuration' in value)) return false;
    return true;
}

export function SubscriptionProductFromJSON(json: any): SubscriptionProduct {
    return SubscriptionProductFromJSONTyped(json, false);
}

export function SubscriptionProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'],
        'gracePeriodDuration': json['grace_period_duration'],
        'trialDuration': json['trial_duration'],
    };
}

export function SubscriptionProductToJSON(value?: SubscriptionProduct | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'duration': value['duration'],
        'grace_period_duration': value['gracePeriodDuration'],
        'trial_duration': value['trialDuration'],
    };
}

