/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Environment } from './Environment';
import {
    instanceOfEnvironment,
    EnvironmentFromJSON,
    EnvironmentFromJSONTyped,
    EnvironmentToJSON,
} from './Environment';

/**
 * @type SubscriptionEnvironment
 * The store environment
 * @export
 */
export type SubscriptionEnvironment = Environment;

export function SubscriptionEnvironmentFromJSON(json: any): SubscriptionEnvironment {
    return SubscriptionEnvironmentFromJSONTyped(json, false);
}

export function SubscriptionEnvironmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionEnvironment {
    if (json == null) {
        return json;
    }
    return { ...EnvironmentFromJSONTyped(json, true) };
}

export function SubscriptionEnvironmentToJSON(value?: SubscriptionEnvironment | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfEnvironment(value)) {
        return EnvironmentToJSON(value as Environment);
    }

    return {};
}

