/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
import type { Product } from "./Product.ts";
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from "./Product.ts";

/**
 * Details about the pending object
 * @export
 * @interface SubscriptionPendingChanges
 */
export interface SubscriptionPendingChanges {
    /**
     * 
     * @type {Product}
     * @memberof SubscriptionPendingChanges
     */
    product?: Product;
}

/**
 * Check if a given object implements the SubscriptionPendingChanges interface.
 */
export function instanceOfSubscriptionPendingChanges(value: object): boolean {
    return true;
}

export function SubscriptionPendingChangesFromJSON(json: any): SubscriptionPendingChanges {
    return SubscriptionPendingChangesFromJSONTyped(json, false);
}

export function SubscriptionPendingChangesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPendingChanges {
    if (json == null) {
        return json;
    }
    return {
        
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
    };
}

export function SubscriptionPendingChangesToJSON(value?: SubscriptionPendingChanges | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'product': ProductToJSON(value['product']),
    };
}

