/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * 
 * @export
 * @interface UpdatePackageRequest
 */
export interface UpdatePackageRequest {
    /**
     * The display name of the package
     * @type {string}
     * @memberof UpdatePackageRequest
     */
    displayName?: string;
    /**
     * The position of the package within the offering
     * @type {number}
     * @memberof UpdatePackageRequest
     */
    position?: number;
}

/**
 * Check if a given object implements the UpdatePackageRequest interface.
 */
export function instanceOfUpdatePackageRequest(value: object): boolean {
    return true;
}

export function UpdatePackageRequestFromJSON(json: any): UpdatePackageRequest {
    return UpdatePackageRequestFromJSONTyped(json, false);
}

export function UpdatePackageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePackageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function UpdatePackageRequestToJSON(value?: UpdatePackageRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'display_name': value['displayName'],
        'position': value['position'],
    };
}

