/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime.ts";
/**
 * 
 * @export
 * @interface UpdateOfferingRequest
 */
export interface UpdateOfferingRequest {
    /**
     * The display name of the offering
     * @type {string}
     * @memberof UpdateOfferingRequest
     */
    displayName?: string;
    /**
     * Indicates if the offering is the current offering
     * @type {boolean}
     * @memberof UpdateOfferingRequest
     */
    isCurrent?: boolean;
    /**
     * Custom metadata of the offering
     * @type {{ [key: string]: string; }}
     * @memberof UpdateOfferingRequest
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the UpdateOfferingRequest interface.
 */
export function instanceOfUpdateOfferingRequest(value: object): boolean {
    return true;
}

export function UpdateOfferingRequestFromJSON(json: any): UpdateOfferingRequest {
    return UpdateOfferingRequestFromJSONTyped(json, false);
}

export function UpdateOfferingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateOfferingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'isCurrent': json['is_current'] == null ? undefined : json['is_current'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateOfferingRequestToJSON(value?: UpdateOfferingRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'display_name': value['displayName'],
        'is_current': value['isCurrent'],
        'metadata': value['metadata'],
    };
}

