/* tslint:disable */
/* eslint-disable */
/**
 * Developer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Play Store type details. Should only be used when type is play_store.
 * @export
 * @interface UpdateAppRequestPlayStore
 */
export interface UpdateAppRequestPlayStore {
    /**
     * The package name of the app
     * @type {string}
     * @memberof UpdateAppRequestPlayStore
     */
    packageName: string;
}

/**
 * Check if a given object implements the UpdateAppRequestPlayStore interface.
 */
export function instanceOfUpdateAppRequestPlayStore(value: object): boolean {
    if (!('packageName' in value)) return false;
    return true;
}

export function UpdateAppRequestPlayStoreFromJSON(json: any): UpdateAppRequestPlayStore {
    return UpdateAppRequestPlayStoreFromJSONTyped(json, false);
}

export function UpdateAppRequestPlayStoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAppRequestPlayStore {
    if (json == null) {
        return json;
    }
    return {
        
        'packageName': json['package_name'],
    };
}

export function UpdateAppRequestPlayStoreToJSON(value?: UpdateAppRequestPlayStore | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'package_name': value['packageName'],
    };
}

